volume_number: 2
isbn: 9784041046555
chapters:
  - title: Distant Back
    subtitle: lost in dark
    parts:
      - title: null
  - title: Season of Budding Flowers
    subtitle: blurry border
    parts:
      - title: An Old Manâ€™s Death
      - title: Cat and Mouse
      - title: Apple and Marshmallow
      - title: Fwedo
      - title: Tiat
  - title: Everything Today Leads to Tomorrow
    subtitle: bottle of elpis
    parts:
      - title: A Special Mission
      - title: Overturned Toy Box
      - title: Special Duty Team
      - title: Tiny Family
  - title: My Most Loved Things, My Most Hated Things
    subtitle: reasons to live
    parts:
      - title: Tiat
      - title: Feodor
      - title: Margo Medicis
      - title: Into the Darkness
      - title: In the Depths of Darkness
  - title: Dreams of the Dead
    subtitle: fragile reunion
    parts:
      - title: null
