volume_number: 1
chapters:
  - title: Chasing After That Back
    subtitle: next to you
    parts:
    - title: null
  - title: The City Waiting for the End
    subtitle: metalcraft miniature garden
    parts:
    - title: The Young Fourth Military Officer
    - title: The Winged Guardâ€™s 5th Division
    - title: The Girls
    - title: Rumors of the Four
  - title: Left and Right Sides of a Breaking Balance
    subtitle: expensive bullet
    parts:
    - title: Disposable Weapons
    - title: Dug Weapon-Compatible Spirits
    - title: A Contentious Pair
    - title: His Real Face
  - title: Chasing, Chasing, After That Admired Back
    subtitle: her blind alley
    parts:
    - title: A Midday Dream
    - title: The Inheritors
    - title: A Battlefield Without Victors
  - title: On These Peaceful Days
    subtitle: offstage of tragedy
    parts:
      - title: null
